services:

  # API + Scheduler + In-process Worker
  - type: web
    name: distributed-job-scheduler-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health

    envVars:
      - key: PORT
        value: "10000"

      - key: STORE_MODE
        value: postgres

      - key: DATABASE_URL
        fromDatabase:
          name: distributed-job-scheduler-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: distributed-job-scheduler-redis
          property: connectionString

      # Scheduler
      - key: SCHEDULER_ENABLED
        value: "true"

      - key: SCHEDULER_INTERVAL
        value: "2s"

      # Worker runs INSIDE the API process
      - key: WORKER_ENABLED
        value: "true"

      - key: WORKER_CONCURRENCY
        value: "4"

      - key: WORKER_ID
        value: "render-api-worker"

      # Leases / heartbeats
      - key: LEASE_DURATION
        value: "30s"

      - key: LEASE_CHECK_INTERVAL
        value: "5s"

      - key: HEARTBEAT_INTERVAL
        value: "10s"

      - key: SEED_DEMO
        value: "true"


  # Redis-compatible Key Value
  - type: keyvalue
    name: distributed-job-scheduler-redis
    plan: free
    ipAllowList: []


databases:

  # PostgreSQL
  - name: distributed-job-scheduler-db
    plan: free